Update data_processing.ipynb to include MPRAGE processing and visalusation
shimming-toolbox/rf-shimming-7t pull request #46
Opened 2024-01-11 20:05 UTC by dpapp86

Clarifies text wrt choice of CoV GRE and MPRAGE for segmentation

fixes #43 
fixes #45 

Various minor comments regarding definition of variables (hard to rerun)

2024-01-11 20:05 UTC, dpapp86 commented
@jcohenadad please review

This should contain everything needed to process MPRAGE scans and create the associated figure

2024-01-13 00:02 UTC, jcohenadad commented on data_processing.ipynb
> +    "path_data = os.getcwd() #works if and only if this is run first and once. Otherwise it will pick up whatever the current directory is if someone wanted to rerun it\n",
That's the motivation for #33

No need to add a comment in the notebook (better to fix #33 instead)

2024-01-13 00:03 UTC, jcohenadad commented on data_processing.ipynb
> +    "subjects = sorted(glob.glob(\"sub-*\")) #Same problem with rerunning it if the cwd is not the ds004906 root\n",
https://github.com/shimming-toolbox/rf-shimming-7t/pull/46/files#r1451039834

2024-01-13 00:04 UTC, jcohenadad commented on data_processing.ipynb
> +    "# Extract B1+ value along the spinal cord between levels C3 and T2 (included)\n",
This change is outside the scope of this PR.

2024-01-13 00:05 UTC, jcohenadad commented on data_processing.ipynb
> +    "        !sct_extract_metric -i {subject}_acq-{shim_mode}_TB1map.nii.gz -f {subject}_acq-anat{shim_mode}_TB1TFL_seg.nii.gz -method wa -vert 3:9 -vertfile {subject}_acq-anat{shim_mode}_TB1TFL_seg_
out of scope

2024-01-13 00:05 UTC, jcohenadad commented on data_processing.ipynb
> +    "original_vector =np.array([907, 870, 833, 800, 769, 735, 692, 646]) # np.array([984, 938, 907, 870, 833, 800, 769, 735, 692, 646])\n",
out of scope

2024-01-13 00:05 UTC, jcohenadad commented on data_processing.ipynb
> +    "    !sct_extract_metric -i {subject}_acq-CoV_T2starw_crop.nii.gz -f {subject}_acq-CoV_T2starw_crop_seg.nii.gz -method wa -vert 3:9 -vertfile {subject}_acq-CoV_T2starw_crop_seg_labeled.nii.gz -ap
This change is outside the scope of this PR.

2024-01-13 00:05 UTC, jcohenadad commented on data_processing.ipynb
> +    "# Extract the signal intensity on the GRE scan within the spinal cord between levels C3 and T2 (included)\n",
This change is outside the scope of this PR.

2024-01-16 02:01 UTC, jcohenadad commented
> also adresses #38

that should go in the PR body-- i've added it

2024-01-16 02:23 UTC, jcohenadad commented on data_processing.ipynb
> +    "    !sct_extract_metric -i {subject}_acq-CoV_T2starw_crop.nii.gz -f {subject}_acq-CoV_T2starw_crop_seg.nii.gz -method wa -vert 3:9 -vertfile {subject}_acq-CoV_T2starw_crop_seg_labeled.nii.gz -ap
Not anymore

2024-01-16 02:47 UTC, jcohenadad reviewed
on https://github.com/shimming-toolbox/rf-shimming-7t/pull/46/commits/36bb2d7a4f6d8d3317eae706d26f713a79386b71 I'm getting:

```console
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[9], line 8
      6 os.chdir(os.path.join(path_data, subject, "anat"))
      7 CoV_flatten=glob.glob(os.path.join(path_data, subject, "anat", f"{subject}_acq-CoV_T1w_crop_flatten.nii.gz"))
----> 8 CoV_flatten=CoV_flatten[0]
      9 CoV_flatten_data=nib.load(CoV_flatten).get_fdata()
     10 CP_flatten=glob.glob(os.path.join(path_data, subject, "anat", f"{subject}_acq-CP_T1w_reg_flatten.nii.gz"))

IndexError: list index out of range
```

False alarm: I forgot to run required cells before :🤦

2024-01-16 03:15 UTC, jcohenadad requested changes
Vertebral labeling failing for sub-02 and sub-04:

![Screenshot 2024-01-15 at 10 15 26 PM](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/d680d240-5172-4501-8415-171fabc891c1)

![Screenshot 2024-01-15 at 10 15 28 PM](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/a656f8d3-5a99-4944-aac4-697f566a4d7a)

2024-01-16 03:45 UTC, jcohenadad approved these changes

2024-01-16 03:46 UTC, merged